#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        services:
          - firefox
          - hub
        script:
          #- mvn clean test
          - mvn clean test -Dtest=LoginPageScenarios -DseleniumHubHost=127.0.0.1
          #- mvn clean test -DsuiteXMLFile=LoginTest.xml -DseleniumHubHost=$seleniumHubHost
          #- echo $MasterKey1
          #- echo google-chrome --version
definitions:
  services:
    firefox:
      environment:
        SE_EVENT_BUS_HOST: 127.0.0.1
        SE_EVENT_BUS_PUBLISH_PORT: 4442
        SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        SE_NODE_OVERRIDE_MAX_SESSIONS: 'true'
        SE_NODE_MAX_SESSIONS: '100'
      image: selenium/node-firefox:99.0
    hub:
      environment:
        SE_OPTS: --host 127.0.0.1 --port 4444 --http-logs true
      image: selenium/hub